# Generated by Django 4.2.7 on 2023-11-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="victimprofile",
            name="identification_type",
        ),
        migrations.AddField(
            model_name="victimprofile",
            name="identification_type",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="victims",
                to="case_interview_app.idtype",
            ),
        ),
    ]
