# Generated by Django 4.2.7 on 2023-11-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0002_remove_victimprofile_identification_type_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Verdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
    ]
