# Generated by Django 4.2.7 on 2023-11-08 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0003_verdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewer",
            name="address",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
