# Generated by Django 4.2.7 on 2023-11-08 21:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0005_approvalstatus_interviewer_approval_comments_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewer",
            name="victim",
        ),
        migrations.AddField(
            model_name="interviewer",
            name="victims",
            field=models.ManyToManyField(
                blank=True, null=True, to="case_interview_app.victimprofile"
            ),
        ),
    ]
