# Generated by Django 4.2.7 on 2023-11-08 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0006_remove_interviewer_victim_interviewer_victims"),
    ]

    operations = [
        migrations.AddField(
            model_name="victimprofile",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="victimprofile",
                to="case_interview_app.approvalstatus",
            ),
        ),
        migrations.AddField(
            model_name="victimprofile",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
