# Generated by Django 4.2.7 on 2023-11-09 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0008_alter_victimprofile_languages"),
    ]

    operations = [
        migrations.AddField(
            model_name="arrestinvestigation",
            name="org_crime",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
