# Generated by Django 4.2.7 on 2023-11-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0011_remove_arrestinvestigation_trafficker"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="arrestinvestigation",
            name="how_traffickers_org",
        ),
        migrations.AddField(
            model_name="arrestinvestigation",
            name="how_traffickers_org",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="investigations",
                to="case_interview_app.traffickerorg",
            ),
        ),
    ]
