# Generated by Django 4.2.7 on 2023-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0014_country_flag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="country",
            name="flag",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
