# Generated by Django 4.2.7 on 2023-11-15 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0015_alter_country_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="VictimPermissions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "interviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="case_interview_app.interviewer",
                    ),
                ),
                (
                    "permissions_granted",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="permissions_granted",
                        to="case_interview_app.accesspermission",
                    ),
                ),
                (
                    "permissions_requested",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="permissions_request",
                        to="case_interview_app.accesspermission",
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="victim_permission",
                        to="case_interview_app.interviewer",
                    ),
                ),
            ],
        ),
    ]
