# Generated by Django 4.2.7 on 2023-11-15 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0017_prosecution_verdict"),
    ]

    operations = [
        migrations.AddField(
            model_name="prosecution",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prosecutions",
                to="case_interview_app.approvalstatus",
            ),
        ),
        migrations.AddField(
            model_name="prosecution",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
    ]
