# Generated by Django 4.2.7 on 2023-11-16 14:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0022_alter_exploitation_debt_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="transitroutedestination",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinations",
                to="case_interview_app.approvalstatus",
            ),
        ),
        migrations.AddField(
            model_name="transitroutedestination",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="transitroutedestination",
            name="city_village_of_dest",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transitroutedestination",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="destinations",
                to="case_interview_app.interviewer",
            ),
        ),
        migrations.AlterField(
            model_name="exploitation",
            name="e_organ_sale_price",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
