# Generated by Django 4.2.7 on 2023-11-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0023_transitroutedestination_approval_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitroutedestination",
            name="means_of_transport",
        ),
        migrations.AddField(
            model_name="transitroutedestination",
            name="means_of_transport",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="destinations",
                to="case_interview_app.transportmean",
            ),
        ),
    ]
