# Generated by Django 4.2.7 on 2023-11-16 14:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0024_remove_transitroutedestination_means_of_transport_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="transitroutedestination",
            name="means_of_transport",
        ),
        migrations.AddField(
            model_name="transitroutedestination",
            name="transport_means",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="transit",
                to="case_interview_app.transportmean",
            ),
        ),
    ]
