# Generated by Django 4.2.7 on 2023-11-18 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0025_remove_transitroutedestination_means_of_transport_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="CommunityAssistanceType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="DataSupplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="EducationLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="FamilyStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="ImEmmigrationStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="IncomeProjectType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LivingWith",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Occupation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Provider",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="SocioEconomic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("violence_prior", models.BooleanField(blank=True, null=True)),
                (
                    "violence_type",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "education_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socio_economic",
                        to="case_interview_app.educationlevel",
                    ),
                ),
                (
                    "family_structure",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socio_economic",
                        to="case_interview_app.familystructure",
                    ),
                ),
                (
                    "last_occupation",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="socio_economic",
                        to="case_interview_app.occupation",
                    ),
                ),
                (
                    "living_with",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socio_economic",
                        to="case_interview_app.livingwith",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AssistanceAggregateData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("total_tip_annually", models.IntegerField(blank=True, null=True)),
                ("total_service", models.IntegerField(blank=True, null=True)),
                ("eligible_family_service", models.IntegerField(blank=True, null=True)),
                ("total_anon_contacts", models.IntegerField(blank=True, null=True)),
                (
                    "data_supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aggregate_data_supplier",
                        to="case_interview_app.datasupplier",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Assistance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("social_assistance_days", models.IntegerField()),
                ("social_assistance_months", models.IntegerField()),
                ("housing_assistance_days", models.IntegerField()),
                ("housing_assistance_months", models.IntegerField()),
                ("housing_allowance_days", models.IntegerField()),
                ("housing_allowance_months", models.IntegerField()),
                ("shelter_days", models.IntegerField()),
                ("shelter_months", models.IntegerField()),
                ("vocational_training_days", models.IntegerField()),
                ("vocational_training_months", models.IntegerField()),
                ("micro_ent_income_days", models.IntegerField()),
                ("micro_ent_income_months", models.IntegerField()),
                ("legal_assistance_days", models.IntegerField()),
                ("legal_assistance_months", models.IntegerField()),
                ("medical_assistance_days", models.IntegerField()),
                ("medical_assistance_months", models.IntegerField()),
                ("financial_assistance_days", models.IntegerField()),
                ("financial_assistance_months", models.IntegerField()),
                ("education_assistance_days", models.IntegerField()),
                ("education_assistance_months", models.IntegerField()),
                ("im_emmigration_assistance_days", models.IntegerField()),
                ("im_emmigration_assistance_months", models.IntegerField()),
                ("other_community_assistance_days", models.IntegerField()),
                ("other_community_assistance_months", models.IntegerField()),
                (
                    "education_assistance_level",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="education_assistance",
                        to="case_interview_app.educationlevel",
                    ),
                ),
                (
                    "education_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="education_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "financial_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="financial_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "housing_allowance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="housing_allowance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "housing_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="housing_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "im_emmigration_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="im_emmigration_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "im_emmigration_assistance_status",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="im_emmigration_assistance",
                        to="case_interview_app.imemmigrationstatus",
                    ),
                ),
                (
                    "legal_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="legal_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "medical_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="medical_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "micro_ent_income_project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="micro_ent_income",
                        to="case_interview_app.incomeprojecttype",
                    ),
                ),
                (
                    "micro_ent_income_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="micro_ent_income",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "other_community_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="other_community_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "other_community_assistance_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="other_community_assistance",
                        to="case_interview_app.communityassistancetype",
                    ),
                ),
                (
                    "shelter_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="shelter",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "social_assistance_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="social_assistance",
                        to="case_interview_app.provider",
                    ),
                ),
                (
                    "vocational_training_provider",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="vocational_training",
                        to="case_interview_app.provider",
                    ),
                ),
            ],
        ),
    ]
