# Generated by Django 4.2.7 on 2023-11-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0026_communityassistancetype_datasupplier_educationlevel_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assistance",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistance",
                to="case_interview_app.approvalstatus",
            ),
        ),
        migrations.AddField(
            model_name="assistance",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistance",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistance",
                to="case_interview_app.interviewer",
            ),
        ),
        migrations.AddField(
            model_name="assistance",
            name="victim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistance",
                to="case_interview_app.victimprofile",
            ),
        ),
        migrations.AddField(
            model_name="assistanceaggregatedata",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistance_aggregate",
                to="case_interview_app.approvalstatus",
            ),
        ),
        migrations.AddField(
            model_name="assistanceaggregatedata",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="assistanceaggregatedata",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assistance_aggregate",
                to="case_interview_app.interviewer",
            ),
        ),
        migrations.AddField(
            model_name="socioeconomic",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socio_economic",
                to="case_interview_app.approvalstatus",
            ),
        ),
        migrations.AddField(
            model_name="socioeconomic",
            name="approval_comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="socioeconomic",
            name="interviewer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socio_economic",
                to="case_interview_app.interviewer",
            ),
        ),
        migrations.AddField(
            model_name="socioeconomic",
            name="victim",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socio_economic",
                to="case_interview_app.victimprofile",
            ),
        ),
    ]
