# Generated by Django 4.2.7 on 2023-11-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0027_assistance_approval_assistance_approval_comments_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="assistance",
            old_name="housing_assistance_days",
            new_name="med_rehab_days",
        ),
        migrations.RenameField(
            model_name="assistance",
            old_name="housing_assistance_months",
            new_name="med_rehab_months",
        ),
        migrations.RemoveField(
            model_name="assistance",
            name="housing_assistance_provider",
        ),
        migrations.AddField(
            model_name="assistance",
            name="med_rehab_provider",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="med_rehab",
                to="case_interview_app.provider",
            ),
        ),
    ]
