# Generated by Django 4.2.7 on 2023-11-18 14:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0028_rename_housing_assistance_days_assistance_med_rehab_days_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="assistance",
            name="halfway_house_days",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="halfway_house",
                to="case_interview_app.provider",
            ),
        ),
    ]
