# Generated by Django 4.2.7 on 2023-11-19 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0030_assistance_halfway_house_months_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="suspectedtrafficker",
            name="id_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
