# Generated by Django 4.2.7 on 2023-11-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0031_alter_suspectedtrafficker_id_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="victimprofile",
            name="victim_identifier",
            field=models.CharField(blank=True, null=True),
        ),
    ]
