# Generated by Django 4.2.7 on 2023-11-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0032_victimprofile_victim_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="victimprofile",
            name="consent_abstain_answer",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="victimprofile",
            name="consent_limited_disclosure",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="victimprofile",
            name="consent_research",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="victimprofile",
            name="consent_share_gov_patner",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
