# Generated by Django 4.2.7 on 2023-11-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0034_tag_search"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="three_code",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="country",
            name="two_code",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
