# Generated by Django 4.2.7 on 2023-11-24 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0035_country_three_code_country_two_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="is_admin",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="is_technical",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
