# Generated by Django 4.2.7 on 2023-11-27 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0037_pendingcase_arrestinvestigation_created_at_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="data_entry_purpose",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="search",
                to="case_interview_app.dataentrypurpose",
            ),
        ),
    ]
