# Generated by Django 4.2.7 on 2023-11-28 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0039_faq"),
    ]

    operations = [
        migrations.AddField(
            model_name="search",
            name="search_description_fr",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="search_description_pt",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="search_text_fr",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="search",
            name="search_text_pt",
            field=models.CharField(blank=True, null=True),
        ),
    ]
