# Generated by Django 4.2.7 on 2023-11-28 19:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0040_search_search_description_fr_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="is_sadc",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
