# Generated by Django 4.2.7 on 2023-12-05 13:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0042_victimprofile_interview_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="interviewer",
            name="address",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="interviewer",
            name="organization",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="interviewer",
            name="position",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
