# Generated by Django 4.2.7 on 2024-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0044_gender_name_en_gender_name_fr_gender_name_pt_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accesspermission",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accesspermission",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="accesspermission",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="affirmoption",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="affirmoption",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="affirmoption",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="approvalstatus",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="approvalstatus",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="approvalstatus",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="aquitalreason",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="aquitalreason",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="aquitalreason",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bodypart",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bodypart",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bodypart",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="brideprice",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="brideprice",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="brideprice",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bridepricerecipient",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bridepricerecipient",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="bridepricerecipient",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="casestatus",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="casestatus",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="casestatus",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="childmarriagereason",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="childmarriagereason",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="childmarriagereason",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="communityassistancetype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="communityassistancetype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="communityassistancetype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="criminalactivitytype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="criminalactivitytype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="criminalactivitytype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dataentrypurpose",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dataentrypurpose",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="dataentrypurpose",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="datasupplier",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="datasupplier",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="datasupplier",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="educationlevel",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exploitationage",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exploitationage",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="exploitationage",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="familystructure",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="familystructure",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="familystructure",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="forcedlabourindustry",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="forcedlabourindustry",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="forcedlabourindustry",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="freedmethod",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="freedmethod",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="freedmethod",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="guiltyreason",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="guiltyreason",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="guiltyreason",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="idtype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="idtype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="idtype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="imemmigrationstatus",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="imemmigrationstatus",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="imemmigrationstatus",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="incomeprojecttype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="incomeprojecttype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="incomeprojecttype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="investigationstatus",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="investigationstatus",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="investigationstatus",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="livingwith",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="livingwith",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="livingwith",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marriageviolencetype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marriageviolencetype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="marriageviolencetype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="militaryactivity",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="militaryactivity",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="militaryactivity",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="militarytype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="militarytype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="militarytype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="occupation",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="occupation",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="occupation",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="operationlocation",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="operationlocation",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="operationlocation",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organpaidto",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organpaidto",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="organpaidto",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="prosecutionoutcome",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="prosecutionoutcome",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="prosecutionoutcome",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="provider",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recruiterrelationship",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recruiterrelationship",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recruiterrelationship",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recruitmenttype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recruitmenttype",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="recruitmenttype",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="roleintrafficking",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="roleintrafficking",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="roleintrafficking",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sanctionpenalty",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sanctionpenalty",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="sanctionpenalty",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="traffickerorg",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="traffickerorg",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="traffickerorg",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="traffickingmean",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="traffickingmean",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="traffickingmean",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transportmean",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transportmean",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="transportmean",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trialcourt",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trialcourt",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="trialcourt",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verdict",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verdict",
            name="name_fr",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="verdict",
            name="name_pt",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
