# Generated by Django 4.2.7 on 2024-03-14 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "case_interview_app",
            "0046_somvictimprofile_somtransitroutedestination_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="somtransitroutedestination",
            name="city_village_of_dest",
        ),
        migrations.RemoveField(
            model_name="somtransitroutedestination",
            name="city_village_of_origin",
        ),
        migrations.AddField(
            model_name="somtransitroutedestination",
            name="countries_of_transit",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="som_transit_countries",
                to="case_interview_app.country",
            ),
        ),
        migrations.AddField(
            model_name="somtransitroutedestination",
            name="country_of_interception",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="som_interception_destinations",
                to="case_interview_app.country",
            ),
        ),
    ]
