# Generated by Django 4.2.7 on 2024-03-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0048_somassistance_education_assistance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="somcase",
            name="role_in_trafficking",
        ),
        migrations.AddField(
            model_name="somsuspectedtrafficker",
            name="date_of_arrest",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="somsuspectedtrafficker",
            name="role_in_trafficking",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="cases",
                to="case_interview_app.roleintrafficking",
            ),
        ),
    ]
