# Generated by Django 4.2.7 on 2024-03-16 17:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0050_exploitation_e_forced_military"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewer",
            name="som_victims",
            field=models.ManyToManyField(
                blank=True, null=True, to="case_interview_app.somvictimprofile"
            ),
        ),
    ]
