# Generated by Django 4.2.7 on 2024-03-17 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0051_interviewer_som_victims"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interviewer",
            name="som_victims",
        ),
        migrations.RemoveField(
            model_name="somcase",
            name="interviewer",
        ),
        migrations.RemoveField(
            model_name="somcase",
            name="victim",
        ),
        migrations.AddField(
            model_name="interviewer",
            name="som_cases",
            field=models.ManyToManyField(
                blank=True, null=True, to="case_interview_app.somcase"
            ),
        ),
        migrations.AddField(
            model_name="somvictimprofile",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="som_victimprofile",
                to="case_interview_app.somcase",
            ),
        ),
    ]
