# Generated by Django 4.2.7 on 2024-03-20 08:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0052_remove_interviewer_som_victims_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="interviewer",
            name="som_victims",
            field=models.ManyToManyField(
                blank=True, null=True, to="case_interview_app.somvictimprofile"
            ),
        ),
    ]
