# Generated by Django 4.2.7 on 2024-04-01 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0053_interviewer_som_victims"),
    ]

    operations = [
        migrations.CreateModel(
            name="SomMultiVictimProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("victim_identifier", models.CharField(blank=True, null=True)),
                ("victim_count", models.IntegerField(blank=True, null=True)),
                (
                    "interview_location",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("interview_date", models.DateField(blank=True, null=True)),
                ("additional_remarks", models.TextField(blank=True, null=True)),
                (
                    "consent_share_gov_patner",
                    models.BooleanField(blank=True, null=True),
                ),
                (
                    "consent_limited_disclosure",
                    models.BooleanField(blank=True, null=True),
                ),
                ("consent_research", models.BooleanField(blank=True, null=True)),
                ("consent_abstain_answer", models.BooleanField(blank=True, null=True)),
                ("approval_comments", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="som_multi_victimprofile",
                        to="case_interview_app.approvalstatus",
                    ),
                ),
                (
                    "case",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="som_multi_victimprofile",
                        to="case_interview_app.somcase",
                    ),
                ),
                (
                    "countries_of_origin",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="som_multi_victim_origin_country",
                        to="case_interview_app.country",
                    ),
                ),
                (
                    "interview_country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="som_multi_victim_interview_country",
                        to="case_interview_app.country",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VictimQuestions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("gender", "Gender"),
                            ("age", "Age"),
                            ("race", "Race"),
                            ("language", "Language"),
                        ],
                        max_length=50,
                    ),
                ),
                ("ordering", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SomVictimAnswers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("answer", models.IntegerField(blank=True, null=True)),
                (
                    "question",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="som_victim_answer",
                        to="case_interview_app.victimquestions",
                    ),
                ),
                (
                    "victim",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="som_victim_answer",
                        to="case_interview_app.sommultivictimprofile",
                    ),
                ),
            ],
        ),
    ]
