# Generated by Django 4.2.7 on 2024-04-29 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("case_interview_app", "0055_remove_somarrestinvestigation_victim_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="somcase",
            name="interview_country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="som_case_interview_country",
                to="case_interview_app.country",
            ),
        ),
        migrations.AddField(
            model_name="somcase",
            name="interview_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="somcase",
            name="interview_location",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
